# Generated by Django 3.0.7 on 2020-06-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20200626_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bed_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='services',
            field=models.TextField(blank=True, null=True),
        ),
    ]
