# Generated by Django 3.0.7 on 2020-06-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
